### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by selgebali** [neternefer/empty_fridge#5]
- [x] Add cuisine @Hdroebuck4 
- [x] Add diet @Hdroebuck4 
- [x] Filter by diet @Hdroebuck4 
- [x] save to file @selgebali 
- [x] order by an attribute if cuisine not specified, order by cuisine/ if cuisine is specified order alphabetically by recipe name @selgebali - hint:sorted() method.
- [x] combine with "beautiful" code from Anna @neternefer 
- [x] code reviews @all 
- [x] Have a GUI - maybe Tkinter @neternefer
